/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.AdminPages;

import Dao.BusDao;
import Dao.DriverDao;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.Bus;
import model.Driver;

/**
 *
 * @author ingab
 */
public class BusMgt extends javax.swing.JInternalFrame {
     DefaultTableModel tableModel = new DefaultTableModel();
    /** Creates new form EmployeeMgt */
    public BusMgt() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
         BusDao dao = new BusDao();
        String id  = dao.generate_busId();
        BusIdTxt.setText(id);
        addTableColumnsHeader();
        addTableRowData();
        
    }
    private void addTableColumnsHeader(){        
        tableModel.addColumn("BusIId");
        tableModel.addColumn("PlateNo");
        tableModel.addColumn("RegisterDate");
        tableModel.addColumn("Bus Size");
        DriverTable.setModel(tableModel);
    }
    
    private void addTableRowData(){
        tableModel.setRowCount(0);
        BusDao busdao = new BusDao();
        List<Bus> buses = busdao.retrieveBuses();
        for(Bus thebus: buses){
            tableModel.addRow(new Object[]{
                thebus.getBus_id(),
                thebus.getPlate_no(),
                thebus.getRegDate(),
                thebus.getSize(),
            });
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        plateNoTxt = new javax.swing.JTextField();
        busSizeTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        DriverTable = new javax.swing.JTable();
        registerBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        searchIdtxt = new javax.swing.JTextField();
        resetBtn = new javax.swing.JButton();
        BusIdTxt = new javax.swing.JLabel();
        registerDateTxt = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 235, 216));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 235, 216));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Plate NO :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel4.setText("Registration Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel6.setText("Size Bus");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel7.setText("BUS ID: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        jPanel1.add(plateNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 120, -1));

        busSizeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busSizeTxtActionPerformed(evt);
            }
        });
        jPanel1.add(busSizeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 120, -1));

        DriverTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(DriverTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 600, 450));

        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        jPanel1.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 616, -1, -1));

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 616, -1, -1));

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 616, -1, -1));

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, -1, -1));
        jPanel1.add(searchIdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 560, 118, -1));

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        jPanel1.add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 620, -1, -1));
        jPanel1.add(BusIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 120, 20));
        jPanel1.add(registerDateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1186, 722));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        if(plateNoTxt.getText().trim().isEmpty() || busSizeTxt.getText().trim().isEmpty() || registerDateTxt == null || registerDateTxt.getDate().toString().trim().isEmpty() || BusIdTxt.getText().trim().isEmpty() ||  BusIdTxt.getText().equalsIgnoreCase("Server Error")  ){
            JOptionPane.showMessageDialog(this, "Plsease Fill All fields","Empty Field",JOptionPane.ERROR_MESSAGE);
            resetBtnActionPerformed(evt);
        }
        else if(!busSizeTxt.getText().matches("\\d+") || plateNoTxt.getText().length() != 7) {
            JOptionPane.showMessageDialog(this, "The Bus Size is a Number \nPlateNo is of length 7\n","Invalid Field",JOptionPane.ERROR_MESSAGE);
            resetBtnActionPerformed(evt);
        }
        else
        {
          Bus bus = new Bus();
          bus.setSize(Integer.parseInt(busSizeTxt.getText()));
          bus.setBus_id(BusIdTxt.getText());
          bus.setPlate_no(plateNoTxt.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
           String date = sdf.format(registerDateTxt.getDate()).toString();
          bus.setRegDate(date);
            
         
          
            DriverDao driverdao = new DriverDao();
            BusDao busdao = new BusDao();
          if(!driverdao.BusExists(BusIdTxt.getText())){
          String feedback = busdao.registerBus(bus);
          JOptionPane.showMessageDialog(this, feedback, "Result", JOptionPane.INFORMATION_MESSAGE);
          addTableRowData();
          resetBtnActionPerformed(evt);
          }
          else{
              JOptionPane.showMessageDialog(this, "The Bus Does Already Exists", "Result", JOptionPane.ERROR_MESSAGE);
          }
        }
        
    }//GEN-LAST:event_registerBtnActionPerformed

    private void busSizeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busSizeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busSizeTxtActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed

         BusDao busdao  = new BusDao();
         Bus bus  = new Bus();
          String id = busdao.generate_busId();
          bus.setBus_id(BusIdTxt.getText());
          if(id.equals(BusIdTxt.getText())){
              JOptionPane.showMessageDialog(this, "Please First Search For the Id","Error",JOptionPane.ERROR_MESSAGE);
          }
          else{
          int  option = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this Bus ?", "Confirm ", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
          if(option == JOptionPane.YES_OPTION){
          String feedback = busdao.deleteBus(bus);
          JOptionPane.showMessageDialog(this, feedback, "Result", JOptionPane.INFORMATION_MESSAGE);
          addTableRowData();
          }
          resetBtnActionPerformed(evt);
          }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        plateNoTxt.setText("");
        busSizeTxt.setText("");
        BusDao busdao = new BusDao();
        BusIdTxt.setText(busdao.generate_busId());
        registerDateTxt.setDate(null);  
        registerBtn.setEnabled(true);
        
    }//GEN-LAST:event_resetBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if(plateNoTxt.getText().trim().isEmpty() || busSizeTxt.getText().trim().isEmpty() || registerDateTxt == null || registerDateTxt.getDate().toString().trim().isEmpty() || BusIdTxt.getText().trim().isEmpty() ||  BusIdTxt.getText().equalsIgnoreCase("Server Error")  ){
            JOptionPane.showMessageDialog(this, "Plsease Fill All fields","Empty Field",JOptionPane.ERROR_MESSAGE);
            resetBtnActionPerformed(evt);
        }
        else if(!busSizeTxt.getText().matches("\\d+") || plateNoTxt.getText().length() != 7) {
            JOptionPane.showMessageDialog(this, "The Bus Size is a Number \nPlateNo is of length 7\n","Invalid Field",JOptionPane.ERROR_MESSAGE);
            resetBtnActionPerformed(evt);
        }
        else
        {
           Bus bus = new Bus();
          bus.setSize(Integer.parseInt(busSizeTxt.getText()));
          bus.setBus_id(BusIdTxt.getText());
          bus.setPlate_no(plateNoTxt.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
           String date = sdf.format(registerDateTxt.getDate()).toString();
          bus.setRegDate(date);
          
            BusDao busdao = new BusDao();
          String feedback = busdao.updateBus(bus);
          JOptionPane.showMessageDialog(this, feedback, "Result", JOptionPane.INFORMATION_MESSAGE);
          addTableRowData();
          resetBtnActionPerformed(evt);
        
        }
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        try{
        if(searchIdtxt.getText().trim().isEmpty()){
             JOptionPane.showMessageDialog(this, "Please Enter Id ","Empty Filed",JOptionPane.ERROR_MESSAGE);
        }
        else if(searchIdtxt.getText().length() == 5 && searchIdtxt.getText().contains("BS")){
            Bus bus = new Bus();
//            Driver driver1 = new Driver();

            BusDao busdao = new BusDao();
            bus.setBus_id(searchIdtxt.getText());
            bus = busdao.searchBus(bus);
            if(bus == null){
                System.out.println(searchIdtxt.getText());
                JOptionPane.showMessageDialog(this, "Id does not Exist", "Result", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                BusIdTxt.setText(bus.getBus_id());
                plateNoTxt.setText(bus.getPlate_no());
                busSizeTxt.setText(bus.getSize().toString());
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                try {
                     registerDateTxt.setDate(sdf.parse(bus.getRegDate()));
                } catch (Exception e) {
                    e.printStackTrace();
                }
               
                registerBtn.setEnabled(false);
            }
            
        }
        }
        
        catch(Exception ex){
                
              ex.printStackTrace();
         }
    }//GEN-LAST:event_searchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BusIdTxt;
    private javax.swing.JTable DriverTable;
    private javax.swing.JTextField busSizeTxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField plateNoTxt;
    private javax.swing.JButton registerBtn;
    private com.toedter.calendar.JDateChooser registerDateTxt;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchIdtxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

}
