/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.AdminPages;

import Dao.CustomerDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.Customer;

/**
 *
 * @author ingab
 */
public class CustomerMgt extends javax.swing.JInternalFrame {
    DefaultTableModel tableModel = new DefaultTableModel();
    
    

    /** Creates new form EmployeeMgt */
    public CustomerMgt() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        addTableColumnsHeader();
        addTableRowData();
        CustomerDao dao = new CustomerDao();
        custIdTxt.setText(dao.generate_custId());
    }  
private void addTableColumnsHeader(){
        tableModel.addColumn("CustomerId");
        tableModel.addColumn("First Name");
        tableModel.addColumn("Last Name");
        tableModel.addColumn("Phone");
        tableModel.addColumn("Gender");
         CustomerTable.setModel(tableModel);
    }
    
    private void addTableRowData(){
        tableModel.setRowCount(0);
        CustomerDao dao = new CustomerDao();
        List<Customer> customers = dao.retrieveCustomers();
        for(Customer thecustomers: customers){
            tableModel.addRow(new Object[]{
                thecustomers.getCust_id(),
                thecustomers.getCust_first_name(),
                thecustomers.getCust_last_name(),
                thecustomers.getCust_phone(),
                thecustomers.getGender()            
            });
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fnameTxt = new javax.swing.JTextField();
        lnameTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        CustomerTable = new javax.swing.JTable();
        registerBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        searchIdtxt = new javax.swing.JTextField();
        genderCombo = new javax.swing.JComboBox<>();
        contactTxt = new javax.swing.JTextField();
        custIdTxt = new javax.swing.JLabel();
        resetBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 235, 216));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 235, 216));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("First Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 89, -1, -1));

        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 151, -1, -1));

        jLabel6.setText("Gender");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 232, -1, -1));

        jLabel7.setText("CUSTOMER ID :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 37, -1, -1));

        jLabel10.setText("Contacts:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 301, -1, -1));
        jPanel1.add(fnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 86, 118, -1));
        jPanel1.add(lnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 148, 118, -1));

        CustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(CustomerTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 740, 460));

        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        jPanel1.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 616, -1, -1));

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 616, -1, -1));

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 616, -1, -1));

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, -1, -1));
        jPanel1.add(searchIdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, 118, -1));

        genderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));
        jPanel1.add(genderCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 229, -1, -1));
        jPanel1.add(contactTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 298, 118, -1));

        custIdTxt.setText("jLabel1");
        jPanel1.add(custIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 120, 30));

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        jPanel1.add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1590, 950));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
         Customer customer = new Customer();

    // Validate input fields before registration
    if (custIdTxt.getText().trim().isEmpty() || fnameTxt.getText().trim().isEmpty() ||
            lnameTxt.getText().trim().isEmpty() || contactTxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please Fill All Fields", "Empty Field", JOptionPane.ERROR_MESSAGE);
        return;
    }

    customer.setCust_id(custIdTxt.getText());
    customer.setCust_first_name(fnameTxt.getText());
    customer.setCust_last_name(lnameTxt.getText());
    customer.setGender(genderCombo.getSelectedItem().toString());
    customer.setCust_phone(contactTxt.getText());

    CustomerDao customerDao = new CustomerDao();
    String feedback = customerDao.RegisterCustomer(customer);

    JOptionPane.showMessageDialog(this, feedback, "Result", JOptionPane.INFORMATION_MESSAGE);
    addTableRowData();

    


    }//GEN-LAST:event_registerBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if (fnameTxt.getText().trim().isEmpty() || lnameTxt.getText().trim().isEmpty() ||
            contactTxt.getText().trim().isEmpty() || genderCombo.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this, "Please Fill All Fields", "Empty Field", JOptionPane.ERROR_MESSAGE);
        resetBtnActionPerformed(evt);
        return;
    }

    // Create a Customer object and set its properties
    Customer customer = new Customer();
    customer.setCust_id(custIdTxt.getText());
    customer.setCust_first_name(fnameTxt.getText());
    customer.setCust_last_name(lnameTxt.getText());
    customer.setGender(genderCombo.getSelectedItem().toString());
    customer.setCust_phone(contactTxt.getText());

    // Create a CustomerDao object and perform the update
    CustomerDao customerDao = new CustomerDao();
    String feedback = customerDao.UpdateCustomer(customer);

    // Display the update result
    JOptionPane.showMessageDialog(this, feedback, "Result", JOptionPane.INFORMATION_MESSAGE);
    addTableRowData();

    }//GEN-LAST:event_updateBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        contactTxt.setText("");
        lnameTxt.setText("");
        fnameTxt.setText("");
        contactTxt.setText("");
        CustomerDao dao = new CustomerDao();
        custIdTxt.setText(dao.generate_custId());
        genderCombo.setSelectedIndex(0);
        registerBtn.setEnabled(true);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
         Customer customer = new Customer();
          CustomerDao jourdao = new CustomerDao();

          String id = jourdao.generate_custId();
          customer.setCust_id(custIdTxt.getText());
          if(id.equals(custIdTxt.getText())){
              JOptionPane.showMessageDialog(this, "Please First Search For the Id","Error",JOptionPane.ERROR_MESSAGE);
          }
          else{
          int  option = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this customer ?", "Confirm ", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
          if(option == JOptionPane.YES_OPTION){
          String feedback = jourdao.deleteCustomer(customer);
          JOptionPane.showMessageDialog(this, feedback, "Result", JOptionPane.INFORMATION_MESSAGE);
          addTableRowData();
          }
          resetBtnActionPerformed(evt);
          }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        try {
    if (searchIdtxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please Enter Customer ID", "Empty Field", JOptionPane.ERROR_MESSAGE);
    } else {
        // Assuming CustomerDao has a method named searchCustomer
        CustomerDao customerDao = new CustomerDao();
        Customer customer = new Customer();
        customer.setCust_id(searchIdtxt.getText());

        // Perform the search
        customer = customerDao.searchCustomer(customer);

        if (customer == null) {
            JOptionPane.showMessageDialog(this, "Customer ID does not Exist", "Result", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Display the customer information in the form fields
            custIdTxt.setText(customer.getCust_id());
            fnameTxt.setText(customer.getCust_first_name());
            lnameTxt.setText(customer.getCust_last_name());
            genderCombo.setSelectedItem(customer.getGender());
            contactTxt.setText(customer.getCust_phone());
            registerBtn.setEnabled(false);

            // Optional: You can perform additional actions if needed
        }
    }
} catch (Exception ex) {
    ex.printStackTrace();
}

    }//GEN-LAST:event_searchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CustomerTable;
    private javax.swing.JTextField contactTxt;
    private javax.swing.JLabel custIdTxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField fnameTxt;
    private javax.swing.JComboBox<String> genderCombo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lnameTxt;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchIdtxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

}
