/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.AdminPages;

import Dao.DriverDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.Driver;

/**
 *
 * @author ingab
 */
public class DriverMgt extends javax.swing.JInternalFrame {
     DefaultTableModel tableModel = new DefaultTableModel();
    /** Creates new form EmployeeMgt */
    public DriverMgt() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
         DriverDao dao = new DriverDao();
        String id  = dao.generate_driverId();
        driverIdtxt.setText(id);
        addTableColumnsHeader();
        addTableRowData();
        
    }
    private void addTableColumnsHeader(){        
        tableModel.addColumn("DriverId");
        tableModel.addColumn("licenceNo");
        tableModel.addColumn("Gender");
        tableModel.addColumn("FName");
        tableModel.addColumn("Lname");
        tableModel.addColumn("phone");
        tableModel.addColumn("salary");
        tableModel.addColumn("busNo"); 
        DriverTable.setModel(tableModel);
    }
    
    private void addTableRowData(){
        tableModel.setRowCount(0);
        DriverDao jourdao = new DriverDao();
        List<Driver> drivers = jourdao.retrieveDrivers();
        for(Driver thedriver: drivers){
            tableModel.addRow(new Object[]{
                thedriver.getDriver_id(),
                thedriver.getLicence_no(),
                thedriver.getGender(),
                thedriver.getF_name(),
                thedriver.getL_name(),
                thedriver.getContact_no(),
                thedriver.getSalary(),
                thedriver.getBus_id(),
            });
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fnameTxt = new javax.swing.JTextField();
        lnameTxt = new javax.swing.JTextField();
        salaryTxt = new javax.swing.JTextField();
        licenceTxt = new javax.swing.JTextField();
        busNoTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        DriverTable = new javax.swing.JTable();
        registerBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        searchIdtxt = new javax.swing.JTextField();
        genderCombo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        resetBtn = new javax.swing.JButton();
        driverIdtxt = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 235, 216));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 235, 216));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("First Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 89, -1, -1));

        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 151, -1, -1));

        jLabel6.setText("Gender");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 232, -1, -1));

        jLabel7.setText("Driver ID: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 37, -1, -1));

        jLabel8.setText("Salary");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 292, -1, -1));

        jLabel9.setText("Driver Licence");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 348, -1, -1));

        jLabel11.setText("Bus No: ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 392, -1, -1));
        jPanel1.add(fnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 86, 120, -1));

        lnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(lnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 148, 120, -1));
        jPanel1.add(salaryTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 289, 120, -1));

        licenceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenceTxtActionPerformed(evt);
            }
        });
        jPanel1.add(licenceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 345, 120, -1));
        jPanel1.add(busNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 389, 120, -1));

        DriverTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(DriverTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 600, 450));

        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        jPanel1.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 616, -1, -1));

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 616, -1, -1));

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 616, -1, -1));

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 580, -1, -1));
        jPanel1.add(searchIdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 580, 118, -1));

        genderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));
        jPanel1.add(genderCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 229, 120, -1));

        jLabel13.setText("Contact Phone");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));
        jPanel1.add(phoneTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 120, -1));

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        jPanel1.add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 620, -1, -1));
        jPanel1.add(driverIdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 120, -1));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1186, 722));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void licenceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenceTxtActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        if(fnameTxt.getText().trim().isEmpty() || lnameTxt.getText().trim().isEmpty() || salaryTxt.getText().trim().isEmpty() || licenceTxt.getText().trim().isEmpty() || busNoTxt.getText().trim().isEmpty() ||  phoneTxt.getText().trim().isEmpty() || genderCombo.getSelectedIndex() == 0 ){
            JOptionPane.showMessageDialog(this, "Plsease Fill All fields","Empty Field",JOptionPane.ERROR_MESSAGE);
            resetBtnActionPerformed(evt);
        }
        else if(!salaryTxt.getText().matches("\\d+(\\.\\d+)?") || busNoTxt.getText().length() != 5 || licenceTxt.getText().length() != 16 || !licenceTxt.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "The salary is a Number \nDriverNo is of length 5\nAnd lecence is 16 digits","Empty Field",JOptionPane.ERROR_MESSAGE);
            resetBtnActionPerformed(evt);
        }
        else
        {
          Driver driver = new Driver();
          driver.setSalary(Double.parseDouble(salaryTxt.getText()));
          driver.setDriver_id(driverIdtxt.getText());
          driver.setF_name(fnameTxt.getText());
          driver.setL_name(lnameTxt.getText());
          driver.setGender(genderCombo.getSelectedItem().toString());
          driver.setLicence_no(licenceTxt.getText());
          driver.setContact_no(phoneTxt.getText());
          
          DriverDao driverdao = new DriverDao();
          if(driverdao.BusExists(busNoTxt.getText())){
          String feedback = driverdao.registerDriver(driver);
          JOptionPane.showMessageDialog(this, feedback, "Result", JOptionPane.INFORMATION_MESSAGE);
          addTableRowData();
          resetBtnActionPerformed(evt);
          }
          else{
              JOptionPane.showMessageDialog(this, "The BusNo("+busNoTxt.getText()+") Does not Exist", "Result", JOptionPane.ERROR_MESSAGE);
          }
        }
        
    }//GEN-LAST:event_registerBtnActionPerformed

    private void lnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameTxtActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed

         DriverDao jourdao = new DriverDao();
         Driver driver  = new Driver();
          String id = jourdao.generate_driverId();
          driver.setDriver_id(driverIdtxt.getText());
          if(id.equals(driverIdtxt.getText())){
              JOptionPane.showMessageDialog(this, "Please First Search For the Id","Error",JOptionPane.ERROR_MESSAGE);
          }
          else{
          int  option = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this driver ?", "Confirm ", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
          if(option == JOptionPane.YES_OPTION){
          String feedback = jourdao.deletDriver(driver);
          JOptionPane.showMessageDialog(this, feedback, "Result", JOptionPane.INFORMATION_MESSAGE);
          addTableRowData();
          }
          resetBtnActionPerformed(evt);
          }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        DriverDao dao = new DriverDao();
        driverIdtxt.setText(dao.generate_driverId());
        fnameTxt.setText("");
        lnameTxt.setText("");
        genderCombo.setSelectedItem("Select");
        salaryTxt.setText("");
        licenceTxt.setText("");
        busNoTxt.setText("");
        phoneTxt.setText("");  
        registerBtn.setEnabled(true);
        
    }//GEN-LAST:event_resetBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
         if(fnameTxt.getText().trim().isEmpty() || lnameTxt.getText().trim().isEmpty() || salaryTxt.getText().trim().isEmpty() || licenceTxt.getText().trim().isEmpty() || busNoTxt.getText().trim().isEmpty() ||  phoneTxt.getText().trim().isEmpty() || genderCombo.getSelectedIndex() == 0 ){
            JOptionPane.showMessageDialog(this, "Plsease Fill All fields","Empty Field",JOptionPane.ERROR_MESSAGE);
            resetBtnActionPerformed(evt);
        }
        else if(!salaryTxt.getText().matches("\\d+(\\.\\d+)?") || busNoTxt.getText().length() != 5 || licenceTxt.getText().length() != 16 || !licenceTxt.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "The salary is a Number \nDriverNo is of length 5\nAnd lecence is 16 digits","Empty Field",JOptionPane.ERROR_MESSAGE);
            resetBtnActionPerformed(evt);
        }
        else
        {
          Driver driver = new Driver();
          driver.setSalary(Double.parseDouble(salaryTxt.getText()));
          driver.setDriver_id(driverIdtxt.getText());
          driver.setF_name(fnameTxt.getText());
          driver.setL_name(lnameTxt.getText());
          driver.setGender(genderCombo.getSelectedItem().toString());
          driver.setLicence_no(licenceTxt.getText());
          driver.setContact_no(phoneTxt.getText());
          driver.setBus_id(busNoTxt.getText());
          
          DriverDao driverdao = new DriverDao();
          if(driverdao.BusExists(busNoTxt.getText())){
          String feedback = driverdao.updateDriver(driver);
          JOptionPane.showMessageDialog(this, feedback, "Result", JOptionPane.INFORMATION_MESSAGE);
          addTableRowData();
          resetBtnActionPerformed(evt);
          }
          else{
              JOptionPane.showMessageDialog(this, "The BusNo("+busNoTxt.getText()+") Does not Exist", "Result", JOptionPane.ERROR_MESSAGE);
          }
        }
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        try{
        if(searchIdtxt.getText().trim().isEmpty()){
             JOptionPane.showMessageDialog(this, "Please Enter Id ","Empty Filed",JOptionPane.ERROR_MESSAGE);
        }
        else if(searchIdtxt.getText().length() == 5 && searchIdtxt.getText().contains("DR")){
            Driver driver = new Driver();
//            Driver driver1 = new Driver();

            DriverDao jourdao = new DriverDao();
            driver.setDriver_id(searchIdtxt.getText());
            driver = jourdao.searchDriver(driver);
            if(driver == null){
                System.out.println(searchIdtxt.getText());
                JOptionPane.showMessageDialog(this, "Id does not Exist", "Result", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                driverIdtxt.setText(driver.getDriver_id());
                fnameTxt.setText(driver.getF_name());
                lnameTxt.setText(driver.getL_name());
                genderCombo.setSelectedItem(driver.getGender());
                phoneTxt.setText(driver.getContact_no());
                salaryTxt.setText(driver.getSalary().toString());
                licenceTxt.setText(driver.getLicence_no());
                busNoTxt.setText(driver.getBus_id());
                registerBtn.setEnabled(false);
            }
            
        }
        }
        
        catch(Exception ex){
                
              ex.printStackTrace();
         }
    }//GEN-LAST:event_searchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DriverTable;
    private javax.swing.JTextField busNoTxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel driverIdtxt;
    private javax.swing.JTextField fnameTxt;
    private javax.swing.JComboBox<String> genderCombo;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField licenceTxt;
    private javax.swing.JTextField lnameTxt;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTextField salaryTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchIdtxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

}
