/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dao.JourneyDao;
import java.awt.Color;
import view.AdminPages.BookTicket;
import view.AdminPages.BusMgt;
import view.AdminPages.CreateJourney;
import view.AdminPages.CustomerMgt;
import view.AdminPages.DriverMgt;
import view.AdminPages.EmployeeMgt;

/**
 *
 * @author ingab
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    Color defaultColor,clickedColor;
    public AdminPage() {
        initComponents();
        defaultColor = new Color(236,227,206);
        clickedColor = new Color(79,111,82);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        CustMgtBtn1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ConfPanel = new javax.swing.JPanel();
        HomeBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CustMgtBtn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DriverMgtBtn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        EmpMgtBtn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BookTickBtn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        creatJournBtn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BusMgtBtn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jDesktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(115, 144, 114));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/icons8-bus-100.png"))); // NOI18N
        jLabel7.setText("Transport Management System");

        CustMgtBtn1.setBackground(new java.awt.Color(236, 227, 206));
        CustMgtBtn1.setMaximumSize(new java.awt.Dimension(137, 82));
        CustMgtBtn1.setMinimumSize(new java.awt.Dimension(137, 82));
        CustMgtBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustMgtBtn1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CustMgtBtn1MousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/icons8-customers-80.png"))); // NOI18N
        jLabel8.setText("Manage Customers");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        javax.swing.GroupLayout CustMgtBtn1Layout = new javax.swing.GroupLayout(CustMgtBtn1);
        CustMgtBtn1.setLayout(CustMgtBtn1Layout);
        CustMgtBtn1Layout.setHorizontalGroup(
            CustMgtBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustMgtBtn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CustMgtBtn1Layout.setVerticalGroup(
            CustMgtBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustMgtBtn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(CustMgtBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(204, 204, 204)
                .addComponent(jLabel7)
                .addGap(304, 304, 304))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustMgtBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 170));

        ConfPanel.setBackground(new java.awt.Color(236, 227, 206));
        ConfPanel.setAutoscrolls(true);
        ConfPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomeBtn.setBackground(new java.awt.Color(236, 227, 206));
        HomeBtn.setMaximumSize(new java.awt.Dimension(137, 82));
        HomeBtn.setMinimumSize(new java.awt.Dimension(137, 82));
        HomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HomeBtnMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/HomeIcon.png"))); // NOI18N
        jLabel1.setText("Home");

        javax.swing.GroupLayout HomeBtnLayout = new javax.swing.GroupLayout(HomeBtn);
        HomeBtn.setLayout(HomeBtnLayout);
        HomeBtnLayout.setHorizontalGroup(
            HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomeBtnLayout.setVerticalGroup(
            HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ConfPanel.add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 309, 72));

        CustMgtBtn.setBackground(new java.awt.Color(236, 227, 206));
        CustMgtBtn.setMaximumSize(new java.awt.Dimension(137, 82));
        CustMgtBtn.setMinimumSize(new java.awt.Dimension(137, 82));
        CustMgtBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustMgtBtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CustMgtBtnMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/icons8-customers-80.png"))); // NOI18N
        jLabel2.setText("Manage Customers");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout CustMgtBtnLayout = new javax.swing.GroupLayout(CustMgtBtn);
        CustMgtBtn.setLayout(CustMgtBtnLayout);
        CustMgtBtnLayout.setHorizontalGroup(
            CustMgtBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustMgtBtnLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CustMgtBtnLayout.setVerticalGroup(
            CustMgtBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );

        ConfPanel.add(CustMgtBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 78, 310, 90));

        DriverMgtBtn.setBackground(new java.awt.Color(236, 227, 206));
        DriverMgtBtn.setMaximumSize(new java.awt.Dimension(137, 82));
        DriverMgtBtn.setMinimumSize(new java.awt.Dimension(137, 82));
        DriverMgtBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DriverMgtBtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DriverMgtBtnMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/icons8-driver-80.png"))); // NOI18N
        jLabel3.setText("Manage Drivers");

        javax.swing.GroupLayout DriverMgtBtnLayout = new javax.swing.GroupLayout(DriverMgtBtn);
        DriverMgtBtn.setLayout(DriverMgtBtnLayout);
        DriverMgtBtnLayout.setHorizontalGroup(
            DriverMgtBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DriverMgtBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        DriverMgtBtnLayout.setVerticalGroup(
            DriverMgtBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DriverMgtBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ConfPanel.add(DriverMgtBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 310, -1));

        EmpMgtBtn.setBackground(new java.awt.Color(236, 227, 206));
        EmpMgtBtn.setMaximumSize(new java.awt.Dimension(137, 82));
        EmpMgtBtn.setMinimumSize(new java.awt.Dimension(137, 82));
        EmpMgtBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpMgtBtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EmpMgtBtnMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/icons8-employee-50.png"))); // NOI18N
        jLabel4.setText("      Manage Employees");

        javax.swing.GroupLayout EmpMgtBtnLayout = new javax.swing.GroupLayout(EmpMgtBtn);
        EmpMgtBtn.setLayout(EmpMgtBtnLayout);
        EmpMgtBtnLayout.setHorizontalGroup(
            EmpMgtBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpMgtBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        EmpMgtBtnLayout.setVerticalGroup(
            EmpMgtBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpMgtBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ConfPanel.add(EmpMgtBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 170, 309, -1));

        BookTickBtn.setBackground(new java.awt.Color(236, 227, 206));
        BookTickBtn.setMaximumSize(new java.awt.Dimension(137, 82));
        BookTickBtn.setMinimumSize(new java.awt.Dimension(137, 82));
        BookTickBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookTickBtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BookTickBtnMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/icons8-ticket-80.png"))); // NOI18N
        jLabel5.setText("Book Ticket");

        javax.swing.GroupLayout BookTickBtnLayout = new javax.swing.GroupLayout(BookTickBtn);
        BookTickBtn.setLayout(BookTickBtnLayout);
        BookTickBtnLayout.setHorizontalGroup(
            BookTickBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookTickBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BookTickBtnLayout.setVerticalGroup(
            BookTickBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookTickBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ConfPanel.add(BookTickBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 309, 90));

        creatJournBtn.setBackground(new java.awt.Color(236, 227, 206));
        creatJournBtn.setMaximumSize(new java.awt.Dimension(137, 82));
        creatJournBtn.setMinimumSize(new java.awt.Dimension(137, 82));
        creatJournBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creatJournBtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                creatJournBtnMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/icons8-journey-80.png"))); // NOI18N
        jLabel6.setText("Create Journey");

        javax.swing.GroupLayout creatJournBtnLayout = new javax.swing.GroupLayout(creatJournBtn);
        creatJournBtn.setLayout(creatJournBtnLayout);
        creatJournBtnLayout.setHorizontalGroup(
            creatJournBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creatJournBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        creatJournBtnLayout.setVerticalGroup(
            creatJournBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creatJournBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ConfPanel.add(creatJournBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 309, 90));

        BusMgtBtn.setBackground(new java.awt.Color(236, 227, 206));
        BusMgtBtn.setMaximumSize(new java.awt.Dimension(137, 82));
        BusMgtBtn.setMinimumSize(new java.awt.Dimension(137, 82));
        BusMgtBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BusMgtBtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BusMgtBtnMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/icons8-driver-80.png"))); // NOI18N
        jLabel9.setText("Manage Buses");

        javax.swing.GroupLayout BusMgtBtnLayout = new javax.swing.GroupLayout(BusMgtBtn);
        BusMgtBtn.setLayout(BusMgtBtnLayout);
        BusMgtBtnLayout.setHorizontalGroup(
            BusMgtBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BusMgtBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        BusMgtBtnLayout.setVerticalGroup(
            BusMgtBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BusMgtBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ConfPanel.add(BusMgtBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 309, -1));

        jPanel1.add(ConfPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 171, 300, 700));

        jDesktopPane.setBackground(new java.awt.Color(79, 111, 82));
        jDesktopPane.setFocusTraversalPolicyProvider(true);
        jDesktopPane.setPreferredSize(new java.awt.Dimension(1020, 700));

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 1010, 700));
        jDesktopPane.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1514, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnMousePressed
        // TODO add your handling code here:
        CustMgtBtn.setBackground(defaultColor);
        HomeBtn.setBackground(clickedColor);
        EmpMgtBtn.setBackground(defaultColor);
        creatJournBtn.setBackground(defaultColor);
        BookTickBtn.setBackground(defaultColor);
        CustMgtBtn1.setBackground(defaultColor);
        DriverMgtBtn.setBackground(defaultColor);
        BusMgtBtn.setBackground(defaultColor);
    }//GEN-LAST:event_HomeBtnMousePressed

    private void CustMgtBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustMgtBtnMousePressed
        // TODO add your handling code here:
   //     System.out.println("Noooo");
        CustMgtBtn.setBackground(clickedColor);
        HomeBtn.setBackground(defaultColor);
        EmpMgtBtn.setBackground(defaultColor);
        creatJournBtn.setBackground(defaultColor);
        BookTickBtn.setBackground(defaultColor);
        DriverMgtBtn.setBackground(defaultColor);
        CustMgtBtn1.setBackground(defaultColor);
        BusMgtBtn.setBackground(defaultColor);
    }//GEN-LAST:event_CustMgtBtnMousePressed

    private void DriverMgtBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DriverMgtBtnMousePressed
        // TODO add your handling code here:
        CustMgtBtn.setBackground(defaultColor);
        HomeBtn.setBackground(defaultColor);
        EmpMgtBtn.setBackground(defaultColor);
        creatJournBtn.setBackground(defaultColor);
        BookTickBtn.setBackground(defaultColor);
        CustMgtBtn1.setBackground(defaultColor);
        DriverMgtBtn.setBackground(clickedColor);
        BusMgtBtn.setBackground(defaultColor);
    }//GEN-LAST:event_DriverMgtBtnMousePressed

    private void EmpMgtBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpMgtBtnMousePressed
        // TODO add your handling code here:
        CustMgtBtn.setBackground(defaultColor);
        HomeBtn.setBackground(defaultColor);
        EmpMgtBtn.setBackground(clickedColor);
        creatJournBtn.setBackground(defaultColor);
        BookTickBtn.setBackground(defaultColor);
        DriverMgtBtn.setBackground(defaultColor);
        CustMgtBtn1.setBackground(defaultColor);
        BusMgtBtn.setBackground(defaultColor);
    }//GEN-LAST:event_EmpMgtBtnMousePressed

    private void BookTickBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookTickBtnMousePressed
        // TODO add your handling code here:
        CustMgtBtn.setBackground(defaultColor);
        HomeBtn.setBackground(defaultColor);
        EmpMgtBtn.setBackground(defaultColor);
        creatJournBtn.setBackground(defaultColor);
        BookTickBtn.setBackground(clickedColor);
        DriverMgtBtn.setBackground(defaultColor);
        CustMgtBtn1.setBackground(defaultColor);
        BusMgtBtn.setBackground(defaultColor);
    }//GEN-LAST:event_BookTickBtnMousePressed

    private void creatJournBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creatJournBtnMousePressed
        // TODO add your handling code here:
        CustMgtBtn.setBackground(defaultColor);
        HomeBtn.setBackground(defaultColor);
        EmpMgtBtn.setBackground(defaultColor);
        creatJournBtn.setBackground(clickedColor);
        BookTickBtn.setBackground(defaultColor);
        DriverMgtBtn.setBackground(defaultColor);
        CustMgtBtn1.setBackground(defaultColor);
        BusMgtBtn.setBackground(defaultColor);
        
    }//GEN-LAST:event_creatJournBtnMousePressed

    private void EmpMgtBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpMgtBtnMouseClicked
        // TODO add your handling code here:
        EmployeeMgt empMgt = new EmployeeMgt();
        jDesktopPane.removeAll();
//        jDesktopPane.repaint();
//        jDesktopPane.revalidate();
        jDesktopPane.add(empMgt).setVisible(true);
    }//GEN-LAST:event_EmpMgtBtnMouseClicked

    private void creatJournBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creatJournBtnMouseClicked
        CreateJourney crj = new CreateJourney();
        jDesktopPane.removeAll();
//        jDesktopPane.repaint();
//        jDesktopPane.revalidate();
        jDesktopPane.add(crj).setVisible(true);
        
        
    }//GEN-LAST:event_creatJournBtnMouseClicked

    private void DriverMgtBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DriverMgtBtnMouseClicked
        // TODO add your handling code here:
            DriverMgt drivMgt = new DriverMgt();
        jDesktopPane.removeAll();
//        jDesktopPane.repaint();
//        jDesktopPane.revalidate();
        jDesktopPane.add(drivMgt).setVisible(true);
    }//GEN-LAST:event_DriverMgtBtnMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
          CustomerMgt custMgt = new CustomerMgt();
        jDesktopPane.removeAll();
//        jDesktopPane.repaint();
//        jDesktopPane.revalidate();
        jDesktopPane.add(custMgt).setVisible(true);
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void CustMgtBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustMgtBtnMouseClicked
//         TODO add your handling code here:
        CustomerMgt custMgt = new CustomerMgt();
        jDesktopPane.removeAll();
//        jDesktopPane.repaint();
//        jDesktopPane.revalidate();
        jDesktopPane.add(custMgt).setVisible(true);
        
    }//GEN-LAST:event_CustMgtBtnMouseClicked

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
           CustMgtBtn.setBackground(clickedColor);
        HomeBtn.setBackground(defaultColor);
        EmpMgtBtn.setBackground(defaultColor);
        creatJournBtn.setBackground(defaultColor);
        BookTickBtn.setBackground(defaultColor);
        DriverMgtBtn.setBackground(defaultColor);
        CustMgtBtn1.setBackground(defaultColor);
        BusMgtBtn.setBackground(defaultColor);
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MousePressed

    private void CustMgtBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustMgtBtn1MouseClicked
        // TODO add your handling code here:
         CustMgtBtn1.setBackground(clickedColor);
        HomeBtn.setBackground(defaultColor);
        EmpMgtBtn.setBackground(defaultColor);
        creatJournBtn.setBackground(defaultColor);
        BookTickBtn.setBackground(defaultColor);
        DriverMgtBtn.setBackground(defaultColor);
        BusMgtBtn.setBackground(defaultColor);
        
    }//GEN-LAST:event_CustMgtBtn1MouseClicked

    private void CustMgtBtn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustMgtBtn1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustMgtBtn1MousePressed

    private void BusMgtBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BusMgtBtnMouseClicked
        // TODO add your handling code here:
         BusMgt busMgt = new BusMgt();
        jDesktopPane.removeAll();
//        jDesktopPane.repaint();
//        jDesktopPane.revalidate();
        jDesktopPane.add(busMgt).setVisible(true);
        
    }//GEN-LAST:event_BusMgtBtnMouseClicked

    private void BusMgtBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BusMgtBtnMousePressed
        // TODO add your handling code here:
         CustMgtBtn1.setBackground(defaultColor);
        HomeBtn.setBackground(defaultColor);
        EmpMgtBtn.setBackground(defaultColor);
        creatJournBtn.setBackground(defaultColor);
        BookTickBtn.setBackground(defaultColor);
        DriverMgtBtn.setBackground(defaultColor);
        BusMgtBtn.setBackground(clickedColor);
       
    }//GEN-LAST:event_BusMgtBtnMousePressed

    private void BookTickBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookTickBtnMouseClicked
        // TODO add your handling code here:
         BookTicket bookticket = new BookTicket();
        jDesktopPane.removeAll();
//        jDesktopPane.repaint();
//        jDesktopPane.revalidate();
        jDesktopPane.add(bookticket).setVisible(true);
    }//GEN-LAST:event_BookTickBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BookTickBtn;
    private javax.swing.JPanel BusMgtBtn;
    private javax.swing.JPanel ConfPanel;
    private javax.swing.JPanel CustMgtBtn;
    private javax.swing.JPanel CustMgtBtn1;
    private javax.swing.JPanel DriverMgtBtn;
    private javax.swing.JPanel EmpMgtBtn;
    private javax.swing.JPanel HomeBtn;
    private javax.swing.JPanel creatJournBtn;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
