/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dao.EmployeeDao;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
//import static javax.swing.Spring.height;
//import static javax.swing.Spring.width;
import model.Employee;

/**
 *
 * @author ingab
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        
         Toolkit tool = Toolkit.getDefaultToolkit();
        Dimension dim = new Dimension(tool.getScreenSize());
        int width = (int) (dim.getWidth() * 0.6);
        int height = (int) (dim.getHeight() * 0.6);
        setSize(width, height);
        setLocation(dim.width / 2 - getWidth() / 2, dim.height / 2 - getHeight() / 2);
    
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        messagetxt = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        passwdTxt = new javax.swing.JPasswordField();
        loginTxt = new javax.swing.JButton();
        resetTxt = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 0));
        setBounds(new java.awt.Rectangle(150, 150, 600, 600));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(198, 151, 116));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.setNextFocusableComponent(this);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 157, 301, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        messagetxt.setBackground(new java.awt.Color(0, 255, 102));
        messagetxt.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        messagetxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messagetxt.setText(" ");
        messagetxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(messagetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 401, 394, -1));
        jPanel1.add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 122, -1));

        passwdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwdTxtActionPerformed(evt);
            }
        });
        jPanel1.add(passwdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 122, -1));

        loginTxt.setBackground(new java.awt.Color(153, 204, 255));
        loginTxt.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        loginTxt.setText("Login");
        loginTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTxtActionPerformed(evt);
            }
        });
        jPanel1.add(loginTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, -1, -1));

        resetTxt.setBackground(new java.awt.Color(204, 153, 255));
        resetTxt.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        resetTxt.setText("Reset");
        resetTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetTxtActionPerformed(evt);
            }
        });
        jPanel1.add(resetTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/icons8-bus-100.png"))); // NOI18N
        jLabel7.setText("Transport Management System");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwdTxtActionPerformed

    private void loginTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTxtActionPerformed
       
        messagetxt.setVisible(true);
        
        if(usernameTxt.getText().trim().isEmpty() || String.valueOf(passwdTxt.getPassword()).trim().isEmpty())
        {
//            messagetxt.setSize(200, 100);
            messagetxt.setForeground(Color.RED);
            messagetxt.setText("Empty Fileds");
        }
        
        else
        {
            EmployeeDao empdao = new EmployeeDao();
            Employee emp = new Employee();
//            emp = null;
            emp.setPasswd(String.valueOf(passwdTxt.getPassword()));
            emp.setUsername(usernameTxt.getText());
            
            Employee emp1 = new Employee();
            emp1 = empdao.loginStatus(emp);
            
//            String role = empdao.loginStatus(emp);
            if(emp1 == null){
                 messagetxt.setForeground(Color.RED);
                 JOptionPane.showMessageDialog(this, "Password or Username does not Exist","Status",JOptionPane.ERROR_MESSAGE);
                 messagetxt.setText("Wrong Username or password"); 
                 resetTxtActionPerformed(evt);
//                 this.setVisible(false);
            }
            else if(emp1.getRole().compareToIgnoreCase("Admin")==0){
                messagetxt.setForeground(Color.GREEN);
                JOptionPane.showMessageDialog(this, "Loged in as Adminstrator(Successfully)","Status",JOptionPane.INFORMATION_MESSAGE);
                messagetxt.setText("Loged in as Adminstrator");
                this.dispose();                
                AdminPage page = new AdminPage();
                page.setVisible(true);
            }
            else if(emp1.getRole().compareToIgnoreCase("user")==0){
                 messagetxt.setForeground(Color.green);
                  JOptionPane.showMessageDialog(this, "Loged in as Normal User (Successfully)","Status",JOptionPane.INFORMATION_MESSAGE);
                messagetxt.setText("Loged in as User");                
                UserPage_new userPage  = new UserPage_new();
                this .dispose();
                userPage.setVisible(true);                            
            }           
            else{
              messagetxt.setForeground(Color.RED);
            JOptionPane.showMessageDialog(this, "Password or Username does not Exist","Status",JOptionPane.ERROR_MESSAGE);
          //  messagetxt.setText("Wrong Username or password"); 
            resetTxtActionPerformed(evt);                  
            }                          
        }
            
    }//GEN-LAST:event_loginTxtActionPerformed

    private void resetTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetTxtActionPerformed
        messagetxt.setVisible(false);
        passwdTxt.setText("");
        usernameTxt.setText("");
    }//GEN-LAST:event_resetTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginTxt;
    private javax.swing.JLabel messagetxt;
    private javax.swing.JPasswordField passwdTxt;
    private javax.swing.JButton resetTxt;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
