/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dao.CustomerDao;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Customer;
import model.Employee;
import sun.util.calendar.JulianCalendar;

/**
 *
 * @author ingab
 */
public class UserPage extends javax.swing.JFrame {

    /**
     * Creates new form userPage
     */
    public UserPage(Employee emp) {
        initComponents();
        province_combo.setSelectedItem("Select Province");
        customerDestinationPanel.setVisible(false);
        
         Toolkit tool = Toolkit.getDefaultToolkit();
        Dimension dim = new Dimension(tool.getScreenSize());
        int height = (int) dim.getHeight();
        int width = (int) dim.getWidth();
        setSize(dim);
        setLocation(width / 2 - getWidth() / 2, height / 2 - getHeight() / 2);
        displayLoginUser.setText("Loged in as "+emp.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UserConfsPanel = new javax.swing.JPanel();
        bookTickectBtn = new javax.swing.JButton();
        bookTickectBtn1 = new javax.swing.JButton();
        bookTickectBtn2 = new javax.swing.JButton();
        bookTickectBtn3 = new javax.swing.JButton();
        displayLoginUser = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        customerInfoPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        customer_fname_txt = new javax.swing.JTextField();
        customer_lname_txt = new javax.swing.JTextField();
        customer_phone_txt = new javax.swing.JTextField();
        customer_info_btn = new javax.swing.JButton();
        customerDestinationPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        journey_date = new com.toedter.calendar.JDateChooser();
        district_combo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        province_combo = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        DestPricetxt = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 51));

        UserConfsPanel.setBackground(new java.awt.Color(102, 51, 255));
        UserConfsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookTickectBtn.setText("Search");
        bookTickectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTickectBtnActionPerformed(evt);
            }
        });
        UserConfsPanel.add(bookTickectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        bookTickectBtn1.setText("Book Ticket");
        bookTickectBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTickectBtn1ActionPerformed(evt);
            }
        });
        UserConfsPanel.add(bookTickectBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        bookTickectBtn2.setText("Book Ticket");
        UserConfsPanel.add(bookTickectBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        bookTickectBtn3.setText("Book Ticket");
        UserConfsPanel.add(bookTickectBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        displayLoginUser.setBackground(new java.awt.Color(153, 255, 153));
        UserConfsPanel.add(displayLoginUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Book Ticket");

        customerInfoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Customer Information");

        jLabel5.setText("First name");

        jLabel6.setText("Last Name:");

        jLabel7.setText("Phone (COntacts) :");

        customer_info_btn.setText("Next");
        customer_info_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_info_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerInfoPanelLayout = new javax.swing.GroupLayout(customerInfoPanel);
        customerInfoPanel.setLayout(customerInfoPanelLayout);
        customerInfoPanelLayout.setHorizontalGroup(
            customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInfoPanelLayout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel4)
                .addContainerGap(355, Short.MAX_VALUE))
            .addGroup(customerInfoPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(106, 106, 106)
                .addGroup(customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customer_phone_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(customer_lname_txt)
                    .addComponent(customer_fname_txt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(customer_info_btn)
                .addGap(54, 54, 54))
        );
        customerInfoPanelLayout.setVerticalGroup(
            customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(customer_fname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(customer_lname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(customer_phone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerInfoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(customer_info_btn)
                .addContainerGap())
        );

        jLabel8.setText("Destination");

        jLabel9.setText("Location");

        jLabel10.setText("Date");

        jLabel11.setText("Time");

        journey_date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                journey_dateMouseClicked(evt);
            }
        });

        district_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                district_comboItemStateChanged(evt);
            }
        });
        district_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                district_comboActionPerformed(evt);
            }
        });

        jLabel12.setText("Province");

        province_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "North", "West", "East", "South" }));
        province_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                province_comboActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "4:00 AM", "6:00 AM", "8:00 AM", "10:00 AM", "12:00 PM", "14:00 PM", "16:00 PM", "18:00 PM", "20:00 PM", "22:00 PM", " ", " ", " " }));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerDestinationPanelLayout = new javax.swing.GroupLayout(customerDestinationPanel);
        customerDestinationPanel.setLayout(customerDestinationPanelLayout);
        customerDestinationPanelLayout.setHorizontalGroup(
            customerDestinationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerDestinationPanelLayout.createSequentialGroup()
                .addGroup(customerDestinationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerDestinationPanelLayout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel8))
                    .addGroup(customerDestinationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(customerDestinationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(132, 132, 132)
                        .addGroup(customerDestinationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customerDestinationPanelLayout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(customerDestinationPanelLayout.createSequentialGroup()
                                .addGroup(customerDestinationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(province_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(journey_date, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(customerDestinationPanelLayout.createSequentialGroup()
                                        .addComponent(district_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(102, 102, 102)
                                        .addComponent(DestPricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(106, 106, 106))
        );
        customerDestinationPanelLayout.setVerticalGroup(
            customerDestinationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerDestinationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerDestinationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(customerDestinationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addGroup(customerDestinationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(province_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(customerDestinationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customerDestinationPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(customerDestinationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(district_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(DestPricetxt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(journey_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerDestinationPanelLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addGroup(customerDestinationPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(customerDestinationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(customerInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(customerDestinationPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addComponent(customerInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(customerDestinationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, "card2");

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Search");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jLabel3)
                .addContainerGap(571, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel3)
                .addContainerGap(773, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, "card2");

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 982, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 866, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserConfsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserConfsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookTickectBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTickectBtn1ActionPerformed

       jPanel2.removeAll();
       jPanel2.repaint();
       jPanel2.revalidate();

       jPanel2.add(jPanel3);
       jPanel2.repaint();
       jPanel2.revalidate();
       
       
       
       
    }//GEN-LAST:event_bookTickectBtn1ActionPerformed

    private void bookTickectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTickectBtnActionPerformed

       jPanel2.removeAll();
       jPanel2.repaint();
       jPanel2.revalidate();
       
       
       jPanel2.add(jPanel4);
       jPanel2.repaint();
       jPanel2.revalidate();
       
       
        
    }//GEN-LAST:event_bookTickectBtnActionPerformed

    private void district_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_district_comboActionPerformed
        
//        customerDestinationPanel.setE
        if(district_combo.getSelectedIndex() != 0 && district_combo.getSelectedItem() != (null))
        {
            journey_date.setEnabled(true);
            
        
//        DestinationDao destdao = new DestinationDao();
        String dest = district_combo.getSelectedItem().toString();
//        String price = "price: "+destdao.generatePrice(dest).toString();
//        DestPricetxt.setText(price);
        }
        
    }//GEN-LAST:event_district_comboActionPerformed

    private void province_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_province_comboActionPerformed
        
        try{
        if(province_combo.getSelectedItem().equals("North")){
            district_combo.removeAllItems();
            district_combo.addItem("Select");
            district_combo.addItem("Musanze");
            district_combo.addItem("Burera");
            district_combo.addItem("Gakenke");
            district_combo.addItem("Rulindo");
            district_combo.addItem("Gicumbi");
            district_combo.setSelectedItem("Select");
        }
        else if(province_combo.getSelectedItem().equals("South")){
            
            district_combo.removeAllItems();
            district_combo.addItem("Select");
            district_combo.addItem("Kamonyi");
            district_combo.addItem("Muhanga");
            district_combo.addItem("Ruhango");
            district_combo.addItem("Nyanza");
//            district_combo.addItem("Gisagara");
            district_combo.addItem("Huye");
            district_combo.addItem("Nyaruguru");
            district_combo.addItem("Nyamagabe");
             district_combo.setSelectedItem("Select Distrit");
        }
        else if(province_combo.getSelectedItem().equals("East")) {
            district_combo.removeAllItems();
            district_combo.addItem("Select");
            district_combo.addItem("Bugesera");
            district_combo.addItem("Rwamagana");
            district_combo.addItem("Kayonza");
            district_combo.addItem("Ngoma");
            district_combo.addItem("Gatsibo");
            district_combo.addItem("Kirehe");
            district_combo.addItem("Nyagatare");            
            
            
        }
         else if(province_combo.getSelectedItem().equals("West")) {
            district_combo.removeAllItems();
            district_combo.addItem("Select");
            district_combo.addItem("Karongi");
            district_combo.addItem("Ngororero");
            district_combo.addItem("Nyabihu");
            district_combo.addItem("Nyamasheke");
            district_combo.addItem("Rubavu");
            district_combo.addItem("Rusizi");
            district_combo.addItem("Rutsiro");                        
            
        }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_province_comboActionPerformed

    private void customer_info_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_info_btnActionPerformed

        if(customer_fname_txt.getText().trim().isEmpty() || customer_lname_txt.getText().trim().isEmpty() || customer_phone_txt.getText().trim().isEmpty()){
            String message = "Please Fill All fields";
            JOptionPane.showMessageDialog(this, message, "Empty Fields",JOptionPane.INFORMATION_MESSAGE);
            
        }
        else
        {
             Customer cust = new Customer();           
            String feedback;
            CustomerDao custDao = new CustomerDao();
            cust.setCust_first_name(customer_fname_txt.getText());
            cust.setCust_last_name(customer_lname_txt.getText());
            cust.setCust_phone(customer_phone_txt.getText());
//            cust.setCust_id(custDao.generate_custId(cust));

                customerInfoPanel.setEnabled(false);
                customerDestinationPanel.setVisible(true);
        }

    }//GEN-LAST:event_customer_info_btnActionPerformed

    private void journey_dateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_journey_dateMouseClicked

        int a  = journey_date.getDate().getMonth();
        JOptionPane.showMessageDialog(this, "a is "+a);
    }//GEN-LAST:event_journey_dateMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

           int a  = journey_date.getDate().getDate();
           JOptionPane.showMessageDialog(this, "a is "+a);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void district_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_district_comboItemStateChanged

//        DestinationDao destdao = new DestinationDao();
//        String dest = district_combo.getSelectedItem().toString();
//        String price = destdao.generatePrice(dest).toString();
//        DestPricetxt.setText(price);
    }//GEN-LAST:event_district_comboItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Employee emp = new Employee();
                emp.setUsername("Olivier");
                new UserPage(emp).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DestPricetxt;
    private javax.swing.JPanel UserConfsPanel;
    private javax.swing.JButton bookTickectBtn;
    private javax.swing.JButton bookTickectBtn1;
    private javax.swing.JButton bookTickectBtn2;
    private javax.swing.JButton bookTickectBtn3;
    private javax.swing.JPanel customerDestinationPanel;
    private javax.swing.JPanel customerInfoPanel;
    private javax.swing.JTextField customer_fname_txt;
    private javax.swing.JButton customer_info_btn;
    private javax.swing.JTextField customer_lname_txt;
    private javax.swing.JTextField customer_phone_txt;
    private javax.swing.JLabel displayLoginUser;
    private javax.swing.JComboBox<String> district_combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private com.toedter.calendar.JDateChooser journey_date;
    private javax.swing.JComboBox<String> province_combo;
    // End of variables declaration//GEN-END:variables
}
